### ISSUE TITLE
Safari errors on Blob constructor

### ISSUE THREAD

**Issue by tomvanrossom** [dougmoscrop/angular-img-http-src#3]
When using in Safari (5.1.7 on Windows10), I get the following error in the console:

` '[object BlobConstructor]' is not a constructor (evaluating 'new Blob(
									[ response.data ], 
									{ type: response.headers('Content-Type') }
								)')`

The image is retrieved, but not displayed.

Chrome, FF and Edge are all working fine without errors!

**Comment by dougmoscrop** [comment]
Safari 5.x does not support Blob constructing (http://caniuse.com/#compare=safari+5.1,safari+6)

Safari 5 is really old and Apple dropped support for it like.. 4 years ago no? (http://appleinsider.com/articles/12/07/25/apple_kills_windows_pc_support_in_safari_60)

**Comment by dougmoscrop** [comment]
Also I am really not sure you want to be using a browser that old for anything!

**Comment by tomvanrossom** [comment]
Sorry, you are right. I did not know Apple does not update Safari for Windows anymore. You can close this ticket

**Comment by dougmoscrop** [comment]
Will do, thanks!
